CLOUDP-209888 Remove temp file creation
mongodb/atlas-sdk-go pull request #233
Opened 2023-11-10 19:13 UTC by fmenezes

## Description

Please include a summary of the fix/feature/change, including any relevant motivation and context.

Link to any related issue(s): 

## Type of change:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Required Checklist:

- [ ] I have signed the [MongoDB CLA](https://www.mongodb.com/legal/contributor-agreement)
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added any necessary documentation (if appropriate)
- [ ] I have run `make fmt` and formatted my code

## Further comments

2023-11-13 09:22 UTC, wtrocki commented
We might need:

- Documentation/good patterns chapter for files
- Change in downloadLogs.go example covering the file usage
- Manual major release bump with Breaking changes explaining the behaviour

2023-11-15 12:32 UTC, wtrocki commented
I see that API still returns File, but PR making changes in interfaces to return closable (which is fine).
![Screenshot 2023-11-15 at 13 30 42](https://github.com/mongodb/atlas-sdk-go/assets/981838/3ba735f1-859f-4358-880c-5b404f2ebe7d)

Do we want to support both File and Closable under some circumstances? Would be able to have one example covering both?

2023-11-15 13:06 UTC, wtrocki approved these changes

2023-11-15 13:19 UTC, wtrocki requested changes
On hold till we release new version today. 
Changes LGTM

2023-11-15 13:20 UTC, wtrocki commented
1. Optional: Add notes to https://github.com/mongodb/atlas-sdk-go/blob/main/docs/doc_5_best_practices.md
2. We will need to Run https://github.com/mongodb/atlas-sdk-go/blob/main/tools/Makefile#L41 to create a new breaking changes file and provide information about breaking changes (let's not do it now as we going to have another major release happening today.

2023-11-15 16:42 UTC, fmenezes commented
@wtrocki I've created https://jira.mongodb.org/browse/CLOUDP-211581

2023-11-15 16:50 UTC, wtrocki approved these changes

2023-11-15 19:51 UTC, kyuan-mongodb approved these changes
LGTM!

2023-11-16 10:00 UTC, merged